baseURL = "https://eikmarizal.netlify.com/"
languageCode = "en-us"
title = "My Portfolio Website"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-XXXXXXXX-Y"

[params]
    theme_color = "#574CDD"
    description = "Portfolio of Eikma Rizal, Data Scientist"
    description_photo = "portfolio.jpg"
    favicon = "favicon.png"
    logo = "logo.png"
    email = "myemail@gmail.com"
    facebook = "eikmarizal"
    twitter = "eikmarizal"
    dribbble = "eikmarizal"
    linkedin = "https://www.linkedin.com/in/eikmarizal"
    medium = "eikmarizal"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar.jpg"
    subtitle = "Hi! I'm Rizal, a Data Scientist from Kuala Lumpur."
    hero_right = ["**Currently doing Data Star Program at ADAX. Previously dev dashboard for senior management at University of Malaya, Malaysia as an data intern.**", "I'm finishing my Bachelor's degree in Computer Science at the University Malaysia Of Computer Science and Engineering , expecting to graduate in 2018."]
    resume = "eikmarizal.pdf"

[params.process]
    enable = true
    title = "My Process"
    subtitle = "Full Process Design"

[params.case_studies]
    enable = true
    title = "Case Studies"
    subtitle = "Selected Works"

[params.footer]
    enable = true
