baseURL = "https://eikmarizal.netlify.com/"
languageCode = "en-us"
title = "My Portfolio Website"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-XXXXXXXX-Y"

[params]
    theme_color = "#574CDD"
    description = "Portfolio of Eikma Rizal, Data Scientist"
    description_photo = "portfolio.jpg"
    favicon = "favicon.png"
    logo = "logo.png"
    email = "myemail@gmail.com"
    facebook = "eikmarizal"
    twitter = "eikmarizal"
    dribbble = "eikmarizal"
    linkedin = "https://www.linkedin.com/in/eikmarizal"
    medium = "eikmarizal"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar.jpg"
    subtitle = "Hi! I'm Eikma Rizal, Junior Data Scientist from Kuala Lumpur."
    hero_right = ["**Currently joined Data Star Program at ADAX.**", "A committed, knowledgeable and capable person. Licensed Certified EC-Council Ethical Hacker (CEH), CompTIA Security+ and Network+. Member of the Student Representative Council as a Vice President of Student Activities, joined several volunteer events including ICT Practitioner Seminar (Legal Issues and Professional Conduct- with Case Studies) as well as a participant in Cyber Security Seminar (Issues & Leveraging Incident Response Teams for Enterprise Security Management). Possess a Bachelor of Computer Science from University Malaysia of Computer Science and Engineering (UniMy) a boutique university devoted to providing a personalised ICT education in a diverse and vibrant community."]
    resume = "eikmarizal.pdf"

[params.process]
    enable = true
    title = "My Process"
    subtitle = "Full Process Design"

[params.case_studies]
    enable = true
    title = "Case Studies"
    subtitle = "Selected Works"

[params.footer]
    enable = true
